---
title: "Wave-take-2"
author: "Andrew Mark"
date: "March 18, 2018"
output:
  html_document: default
  pdf_document: default
---

```{r}
library(curl)
library(ggplot2)
library(dplyr)
library(gridExtra)
library(manipulate)
library(lmodel2)
library(ggmap)
```
```{r}
f <- curl("https://raw.githubusercontent.com/andym5780/Wave-of-Advance-Andy/master/Take-2.csv")
dm <- read.csv(f, header = TRUE)
head(dm)
```
```{r}
dm
```



```{r}
m <- lm(Average.Year ~ Distance.km., data = dm)
m
```
```{r}
m <- lm(Average.Year ~ Distance.km., data = dm)
h_hat <- predict(m, newdata = data.frame(Distance.km. = dm$Distance.km.))
df <- data.frame(cbind(dm$Distance.km., dm$Average.Year, h_hat))
names(df) <- c("x", "y", "yhat")
df<-tbl_df(df)
df<-mutate(df,Site=dm$Site)
head(df)
```
```{r}
g <- ggplot(data = df, aes(x = x, y = yhat))
g <- g + geom_point()
g <- g + geom_point(aes(x = x, y = y), colour = "red")
g <- g + geom_segment(aes(x = x, y = yhat, xend = x, yend = y))
g
```

```{r}
ci <- predict(m, newdata = data.frame(Distance.km. = dm$Distance.km.), interval = "confidence", 
    level = 0.95)  # for a vector of values
head(ci)
```
```{r}
df <- mutate(df,CIfit=ci[,1],CIlwr=ci[,2],CIupr=ci[,3])
head(df)
```

```{r}
g <- ggplot(data = df, aes(x = x, y = y))
g <- g + geom_point(alpha = 1/2)
g <- g + geom_line(aes(x = x, y = CIfit), colour = "black")
g <- g + geom_line(aes(x = x, y = CIlwr), colour = "blue")
g <- g + geom_line(aes(x = x, y = CIupr), colour = "blue")
g
```

```{r}
coef(m)
```

```{r}
confint(m)
```

```{r}
summary(m)
```

The r-value is 0.41012, the new P-value is 0.01599, the slope of the line is -2.143996 year/km with a CI of -3.86061 to -0.4273816 year/km which coresponds to 0.4664187 km/year and a CI of 0.25903 to 2.339829 km/ year.  this places it outside of the predicted range of 0.545-0.999998 ≈ 1 kilometers per year. there are 34 sites



